'use client'

import { useState, useMemo } from 'react'
import { MainLayout } from '@/components/layout/MainLayout'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useStore } from '@/store/useStore'
import { formatCurrency } from '@/lib/utils'
import { Plus, Calendar as CalendarIcon, Upload, FileText, Download, Trash2, Edit, Save, X, RefreshCw } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import type { FinancialEvent, Document } from '@/types'
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay, isSameMonth, addMonths, parseISO } from 'date-fns'
import { ptBR } from 'date-fns/locale'

export default function CalendarPage() {
  const { debts, fixedExpenses, paymentPlans } = useStore()
  const [currentDate, setCurrentDate] = useState(new Date())
  const [customEvents, setCustomEvents] = useState<FinancialEvent[]>([])
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [selectedEvent, setSelectedEvent] = useState<FinancialEvent | null>(null)
  const [formData, setFormData] = useState<Partial<FinancialEvent>>({
    title: '',
    date: format(new Date(), 'yyyy-MM-dd'),
    type: 'payment',
    status: 'pending',
  })
  const [autoSync, setAutoSync] = useState(true)

  // Gerar eventos automáticos das dívidas
  const autoGeneratedEvents = useMemo(() => {
    const events: FinancialEvent[] = []

    // Eventos das dívidas
    debts
      .filter((d) => d.status === 'active')
      .forEach((debt) => {
        // Se tem data de vencimento
        if (debt.dueDate) {
          events.push({
            id: `debt-${debt.id}-due`,
            title: `Vencimento: ${debt.name}`,
            description: `Valor: ${formatCurrency(debt.type === 'money' ? debt.value : debt.entryValue || 0)}`,
            date: debt.dueDate,
            type: 'deadline',
            amount: debt.type === 'money' ? debt.value : debt.entryValue || 0,
            category: 'Dívida',
            status: 'pending',
            relatedDebtId: debt.id,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          })
        }

        // Se tem plano de pagamento parcelado
        if (debt.paymentPlan) {
          const { monthlyValue, installments, currentInstallment, startDate } = debt.paymentPlan
          const start = parseISO(startDate)

          for (let i = currentInstallment; i <= installments; i++) {
            const paymentDate = addMonths(start, i - 1)
            events.push({
              id: `debt-${debt.id}-installment-${i}`,
              title: `Parcela ${i}/${installments}: ${debt.name}`,
              description: `Pagamento parcelado - ${formatCurrency(monthlyValue)}`,
              date: format(paymentDate, 'yyyy-MM-dd'),
              type: 'payment',
              amount: monthlyValue,
              category: 'Dívida Parcelada',
              status: i < currentInstallment ? 'completed' : 'pending',
              relatedDebtId: debt.id,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            })
          }
        } else if (!debt.dueDate) {
          // Se não tem data nem plano, criar evento genérico para este mês
          events.push({
            id: `debt-${debt.id}-pending`,
            title: `Pendente: ${debt.name}`,
            description: `Valor total: ${formatCurrency(debt.type === 'money' ? debt.value : debt.entryValue || 0)}`,
            date: format(new Date(), 'yyyy-MM-dd'),
            type: 'payment',
            amount: debt.type === 'money' ? debt.value : debt.entryValue || 0,
            category: 'Dívida',
            status: 'pending',
            relatedDebtId: debt.id,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          })
        }

        // Entradas de cartas
        if (debt.type === 'card' && debt.entryValue) {
          events.push({
            id: `debt-${debt.id}-entry`,
            title: `Entrada Carta: ${debt.name}`,
            description: `Entrada de ${formatCurrency(debt.entryValue)} (30% de ${formatCurrency(debt.cardValue || 0)})`,
            date: debt.dueDate || format(new Date(), 'yyyy-MM-dd'),
            type: 'payment',
            amount: debt.entryValue,
            category: 'Entrada Carta',
            status: 'pending',
            relatedDebtId: debt.id,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          })
        }
      })

    // Eventos das despesas fixas
    fixedExpenses
      .filter((e) => e.status === 'active')
      .forEach((expense) => {
        const start = parseISO(expense.startDate)
        const end = parseISO(expense.endDate)
        let current = new Date(start)

        while (current <= end) {
          events.push({
            id: `expense-${expense.id}-${format(current, 'yyyy-MM')}`,
            title: expense.name,
            description: `Despesa fixa mensal`,
            date: format(current, 'yyyy-MM-dd'),
            type: 'payment',
            amount: expense.monthlyValue,
            category: expense.category || 'Despesa Fixa',
            status: current < new Date() ? 'completed' : 'pending',
            relatedExpenseId: expense.id,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          })

          current = addMonths(current, 1)
        }
      })

    // Eventos do plano de pagamento
    paymentPlans.forEach((plan) => {
      const planDate = parseISO(plan.month + '-01')
      
      // Receita
      events.push({
        id: `plan-${plan.month}-revenue`,
        title: 'Receita Mensal',
        description: `Comissão do mês`,
        date: format(planDate, 'yyyy-MM-dd'),
        type: 'receipt',
        amount: plan.revenue,
        category: 'Receita',
        status: 'pending',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })

      // Pagamentos planejados
      plan.payments.forEach((payment, idx) => {
        events.push({
          id: `plan-${plan.month}-payment-${idx}`,
          title: `Pagamento: ${payment.debtName}`,
          description: `Plano de pagamento`,
          date: format(planDate, 'yyyy-MM-dd'),
          type: 'payment',
          amount: payment.amount,
          category: 'Plano de Pagamento',
          status: 'pending',
          relatedDebtId: payment.debtId,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        })
      })
    })

    return events
  }, [debts, fixedExpenses, paymentPlans])

  // Combinar eventos automáticos com eventos customizados
  const allEvents = useMemo(() => {
    if (autoSync) {
      // Mesclar eventos, priorizando customizados
      const autoIds = new Set(autoGeneratedEvents.map((e) => e.id))
      const customOnly = customEvents.filter((e) => !autoIds.has(e.id))
      return [...autoGeneratedEvents, ...customOnly]
    }
    return customEvents
  }, [autoSync, autoGeneratedEvents, customEvents])

  const monthStart = startOfMonth(currentDate)
  const monthEnd = endOfMonth(currentDate)
  const days = eachDayOfInterval({ start: monthStart, end: monthEnd })

  const handleOpenDialog = (event?: FinancialEvent, date?: Date) => {
    if (event) {
      setSelectedEvent(event)
      setFormData(event)
    } else {
      setSelectedEvent(null)
      setFormData({
        title: '',
        date: date ? format(date, 'yyyy-MM-dd') : format(new Date(), 'yyyy-MM-dd'),
        type: 'payment',
        status: 'pending',
      })
    }
    setIsDialogOpen(true)
  }

  const handleSave = () => {
    const newEvent: FinancialEvent = {
      id: selectedEvent?.id || Date.now().toString(),
      title: formData.title || '',
      description: formData.description,
      date: formData.date || format(new Date(), 'yyyy-MM-dd'),
      type: formData.type || 'payment',
      amount: formData.amount,
      category: formData.category,
      status: formData.status || 'pending',
      attachments: formData.attachments || [],
      relatedDebtId: formData.relatedDebtId,
      relatedExpenseId: formData.relatedExpenseId,
      createdAt: selectedEvent?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }

    if (selectedEvent) {
      setCustomEvents(customEvents.map((e) => (e.id === selectedEvent.id ? newEvent : e)))
    } else {
      setCustomEvents([...customEvents, newEvent])
    }

    setIsDialogOpen(false)
    setSelectedEvent(null)
  }

  const handleDelete = (id: string) => {
    if (confirm('Tem certeza que deseja remover este evento?')) {
      setCustomEvents(customEvents.filter((e) => e.id !== id))
    }
  }

  const getEventsForDate = (date: Date) => {
    return allEvents.filter((e) => isSameDay(parseISO(e.date), date))
  }

  const getEventColor = (type: string) => {
    switch (type) {
      case 'payment':
        return 'bg-prospere-red text-white'
      case 'receipt':
        return 'bg-green-500 text-white'
      case 'deadline':
        return 'bg-yellow-500 text-white'
      case 'meeting':
        return 'bg-blue-500 text-white'
      default:
        return 'bg-gray-500 text-white'
    }
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">Calendário Financeiro</h1>
            <p className="text-muted-foreground">
              Sincronizado automaticamente com dívidas, despesas e planos de pagamento
            </p>
          </div>
          <div className="flex gap-2">
            <div className="flex items-center gap-2 px-4 py-2 border rounded-lg">
              <input
                type="checkbox"
                id="autoSync"
                checked={autoSync}
                onChange={(e) => setAutoSync(e.target.checked)}
                className="h-4 w-4"
              />
              <Label htmlFor="autoSync" className="cursor-pointer">
                Sincronização Automática
              </Label>
            </div>
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
              <DialogTrigger asChild>
                <Button onClick={() => handleOpenDialog()}>
                  <Plus className="mr-2 h-4 w-4" />
                  Novo Evento
                </Button>
              </DialogTrigger>
            <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>{selectedEvent ? 'Editar Evento' : 'Novo Evento'}</DialogTitle>
                <DialogDescription>
                  Adicione um evento financeiro ao calendário
                </DialogDescription>
              </DialogHeader>

              <div className="space-y-4 py-4">
                <div>
                  <Label htmlFor="title">Título</Label>
                  <Input
                    id="title"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    placeholder="Ex: Pagamento Raul, Recebimento comissão..."
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="date">Data</Label>
                    <Input
                      id="date"
                      type="date"
                      value={formData.date}
                      onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                    />
                  </div>
                  <div>
                    <Label htmlFor="type">Tipo</Label>
                    <Select
                      value={formData.type}
                      onValueChange={(value) => setFormData({ ...formData, type: value as any })}
                    >
                      <SelectTrigger id="type">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="payment">Pagamento</SelectItem>
                        <SelectItem value="receipt">Recebimento</SelectItem>
                        <SelectItem value="deadline">Prazo</SelectItem>
                        <SelectItem value="meeting">Reunião</SelectItem>
                        <SelectItem value="reminder">Lembrete</SelectItem>
                        <SelectItem value="other">Outro</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="amount">Valor (R$)</Label>
                    <Input
                      id="amount"
                      type="number"
                      value={formData.amount || 0}
                      onChange={(e) => setFormData({ ...formData, amount: Number(e.target.value) })}
                    />
                  </div>
                  <div>
                    <Label htmlFor="status">Status</Label>
                    <Select
                      value={formData.status}
                      onValueChange={(value) => setFormData({ ...formData, status: value as any })}
                    >
                      <SelectTrigger id="status">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="pending">Pendente</SelectItem>
                        <SelectItem value="completed">Concluído</SelectItem>
                        <SelectItem value="cancelled">Cancelado</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div>
                  <Label htmlFor="description">Descrição</Label>
                  <Textarea
                    id="description"
                    value={formData.description || ''}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    placeholder="Detalhes do evento"
                  />
                </div>
              </div>

              <DialogFooter>
                <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
                  <X className="mr-2 h-4 w-4" />
                  Cancelar
                </Button>
                <Button onClick={handleSave} disabled={!formData.title}>
                  <Save className="mr-2 h-4 w-4" />
                  Salvar
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        {/* Navegação do Calendário */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>
                {format(currentDate, 'MMMM yyyy', { locale: ptBR })}
              </CardTitle>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1))}
                >
                  Anterior
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentDate(new Date())}
                >
                  Hoje
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1))}
                >
                  Próximo
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-7 gap-2 mb-2">
              {['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map((day) => (
                <div key={day} className="text-center font-semibold text-sm text-muted-foreground p-2">
                  {day}
                </div>
              ))}
            </div>
            <div className="grid grid-cols-7 gap-2">
              {days.map((day) => {
                const dayEvents = getEventsForDate(day)
                const isCurrentMonth = isSameMonth(day, currentDate)
                const isToday = isSameDay(day, new Date())

                return (
                  <div
                    key={day.toISOString()}
                    className={`min-h-[100px] border rounded-lg p-2 ${
                      !isCurrentMonth ? 'opacity-30' : ''
                    } ${isToday ? 'bg-blue-50 border-blue-500' : ''}`}
                  >
                    <div className={`text-sm font-medium mb-1 ${isToday ? 'text-blue-600' : ''}`}>
                      {format(day, 'd')}
                    </div>
                    <div className="space-y-1">
                      {dayEvents.slice(0, 3).map((event) => {
                        const isAuto = autoGeneratedEvents.some((e) => e.id === event.id)
                        return (
                          <div
                            key={event.id}
                            className={`text-xs p-1 rounded ${getEventColor(event.type)} cursor-pointer ${
                              isAuto ? 'opacity-90' : ''
                            }`}
                            onClick={() => !isAuto && handleOpenDialog(event)}
                            title={event.title + (isAuto ? ' (Automático)' : '')}
                          >
                            {event.title}
                          </div>
                        )
                      })}
                      {dayEvents.length > 3 && (
                        <div className="text-xs text-muted-foreground">
                          +{dayEvents.length - 3} mais
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </CardContent>
        </Card>

        {/* Estatísticas */}
        <div className="grid gap-4 md:grid-cols-4">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Eventos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {allEvents.filter((e) => isSameMonth(parseISO(e.date), currentDate)).length}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Pagamentos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-prospere-red">
                {formatCurrency(
                  allEvents
                    .filter((e) => isSameMonth(parseISO(e.date), currentDate) && e.type === 'payment')
                    .reduce((sum, e) => sum + (e.amount || 0), 0)
                )}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Recebimentos</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">
                {formatCurrency(
                  allEvents
                    .filter((e) => isSameMonth(parseISO(e.date), currentDate) && e.type === 'receipt')
                    .reduce((sum, e) => sum + (e.amount || 0), 0)
                )}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Saldo do Mês</CardTitle>
            </CardHeader>
            <CardContent>
              <div
                className={`text-2xl font-bold ${
                  allEvents
                    .filter((e) => isSameMonth(parseISO(e.date), currentDate))
                    .reduce((sum, e) => {
                      if (e.type === 'receipt') return sum + (e.amount || 0)
                      if (e.type === 'payment') return sum - (e.amount || 0)
                      return sum
                    }, 0) >= 0
                    ? 'text-green-600'
                    : 'text-prospere-red'
                }`}
              >
                {formatCurrency(
                  allEvents
                    .filter((e) => isSameMonth(parseISO(e.date), currentDate))
                    .reduce((sum, e) => {
                      if (e.type === 'receipt') return sum + (e.amount || 0)
                      if (e.type === 'payment') return sum - (e.amount || 0)
                      return sum
                    }, 0)
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Lista de Eventos do Mês */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Eventos de {format(currentDate, 'MMMM yyyy', { locale: ptBR })}</CardTitle>
              <div className="text-sm text-muted-foreground">
                {autoGeneratedEvents.filter((e) => isSameMonth(parseISO(e.date), currentDate)).length} automáticos
                {customEvents.filter((e) => isSameMonth(parseISO(e.date), currentDate)).length > 0 &&
                  ` • ${customEvents.filter((e) => isSameMonth(parseISO(e.date), currentDate)).length} customizados`}
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {allEvents
                .filter((e) => isSameMonth(parseISO(e.date), currentDate))
                .sort((a, b) => parseISO(a.date).getTime() - parseISO(b.date).getTime())
                .map((event) => {
                  const isAutoGenerated = autoGeneratedEvents.some((e) => e.id === event.id)
                  return (
                    <div key={event.id} className="flex items-center justify-between p-4 border rounded-lg">
                      <div className="flex items-center gap-4 flex-1">
                        <div className={`w-3 h-3 rounded-full ${getEventColor(event.type)}`} />
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            <h3 className="font-semibold">{event.title}</h3>
                            {isAutoGenerated && (
                              <span className="px-2 py-1 rounded text-xs bg-blue-100 text-blue-800">
                                Automático
                              </span>
                            )}
                            <span className={`px-2 py-1 rounded text-xs ${getEventColor(event.type)}`}>
                              {event.type === 'payment' ? 'Pagamento' : event.type === 'receipt' ? 'Recebimento' : event.type === 'deadline' ? 'Prazo' : event.type}
                            </span>
                            <span
                              className={`px-2 py-1 rounded text-xs ${
                                event.status === 'completed'
                                  ? 'bg-green-500 text-white'
                                  : event.status === 'pending'
                                  ? 'bg-yellow-500 text-white'
                                  : 'bg-gray-500 text-white'
                              }`}
                            >
                              {event.status === 'completed' ? 'Concluído' : event.status === 'pending' ? 'Pendente' : 'Cancelado'}
                            </span>
                          </div>
                          <p className="text-sm text-muted-foreground mt-1">
                            {format(parseISO(event.date), "dd 'de' MMMM 'de' yyyy", { locale: ptBR })}
                            {event.amount && ` • ${formatCurrency(event.amount)}`}
                          </p>
                          {event.description && (
                            <p className="text-sm text-muted-foreground mt-1">{event.description}</p>
                          )}
                          {event.category && (
                            <p className="text-xs text-muted-foreground mt-1">Categoria: {event.category}</p>
                          )}
                        </div>
                      </div>
                      {!isAutoGenerated && (
                        <div className="flex gap-2">
                          <Button variant="ghost" size="sm" onClick={() => handleOpenDialog(event)}>
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => handleDelete(event.id)}>
                            <Trash2 className="h-4 w-4 text-prospere-red" />
                          </Button>
                        </div>
                      )}
                    </div>
                  )
                })}
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  )
}
